services:
  backend:
    build: { target: development }
    develop:
      watch:
        - action: sync+restart
          path: ./backend
          target: /src
          ignore:
            - .git/
        - action: rebuild
          path: ./backend/go.mod

  frontend:
    build: { target: development }
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
            - .next/
        - action: rebuild
          path: ./frontend/pnpm-lock.yaml
        - action: rebuild
          path: ./frontend/package.json
