services:
  backend:
    build: { target: development }
    environment:
      COOKIE_SECURE: "false"
    develop:
      watch:
        - action: sync+restart
          path: ./backend
          target: /src
          ignore:
            - .git/
        - action: rebuild
          path: ./backend/go.mod
