// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_log.sql

package db

import (
	"context"
)

const countEventLog = `-- name: CountEventLog :one
SELECT COUNT(*) FROM event_log
`

func (q *Queries) CountEventLog(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countEventLog)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertEventLog = `-- name: InsertEventLog :exec
INSERT INTO event_log (event_name, payload) VALUES ($1, $2)
`

type InsertEventLogParams struct {
	EventName string
	Payload   []byte
}

func (q *Queries) InsertEventLog(ctx context.Context, arg InsertEventLogParams) error {
	_, err := q.db.Exec(ctx, insertEventLog, arg.EventName, arg.Payload)
	return err
}

const listEventLog = `-- name: ListEventLog :many
SELECT id, event_name, payload, occurred_at
FROM event_log
ORDER BY occurred_at DESC, id DESC
LIMIT $2 OFFSET $1
`

type ListEventLogParams struct {
	PageOffset int32
	PageLimit  int32
}

func (q *Queries) ListEventLog(ctx context.Context, arg ListEventLogParams) ([]EventLog, error) {
	rows, err := q.db.Query(ctx, listEventLog, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventLog{}
	for rows.Next() {
		var i EventLog
		if err := rows.Scan(
			&i.ID,
			&i.EventName,
			&i.Payload,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
