// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: healer.sql

package db

import (
	"context"
)

const countHealerByDistrict = `-- name: CountHealerByDistrict :one
SELECT COUNT(*) FROM healer WHERE district_id = $1
`

func (q *Queries) CountHealerByDistrict(ctx context.Context, districtID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countHealerByDistrict, districtID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createHealer = `-- name: CreateHealer :one
INSERT INTO healer (district_id, full_name, sub_district, specialty, biography)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, district_id, full_name, sub_district, specialty, biography, created_at, updated_at
`

type CreateHealerParams struct {
	DistrictID  int64
	FullName    string
	SubDistrict string
	Specialty   string
	Biography   string
}

func (q *Queries) CreateHealer(ctx context.Context, arg CreateHealerParams) (Healer, error) {
	row := q.db.QueryRow(ctx, createHealer,
		arg.DistrictID,
		arg.FullName,
		arg.SubDistrict,
		arg.Specialty,
		arg.Biography,
	)
	var i Healer
	err := row.Scan(
		&i.ID,
		&i.DistrictID,
		&i.FullName,
		&i.SubDistrict,
		&i.Specialty,
		&i.Biography,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteHealer = `-- name: DeleteHealer :execrows
DELETE FROM healer WHERE id = $1
`

func (q *Queries) DeleteHealer(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteHealer, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getHealer = `-- name: GetHealer :one
SELECT id, district_id, full_name, sub_district, specialty, biography, created_at, updated_at
FROM healer
WHERE id = $1
`

func (q *Queries) GetHealer(ctx context.Context, id int64) (Healer, error) {
	row := q.db.QueryRow(ctx, getHealer, id)
	var i Healer
	err := row.Scan(
		&i.ID,
		&i.DistrictID,
		&i.FullName,
		&i.SubDistrict,
		&i.Specialty,
		&i.Biography,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listHealerByDistrictPage = `-- name: ListHealerByDistrictPage :many
SELECT id, district_id, full_name, sub_district, specialty, biography, created_at, updated_at
FROM healer
WHERE district_id = $1
ORDER BY full_name
LIMIT $3 OFFSET $2
`

type ListHealerByDistrictPageParams struct {
	DistrictID int64
	PageOffset int32
	PageLimit  int32
}

func (q *Queries) ListHealerByDistrictPage(ctx context.Context, arg ListHealerByDistrictPageParams) ([]Healer, error) {
	rows, err := q.db.Query(ctx, listHealerByDistrictPage, arg.DistrictID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Healer{}
	for rows.Next() {
		var i Healer
		if err := rows.Scan(
			&i.ID,
			&i.DistrictID,
			&i.FullName,
			&i.SubDistrict,
			&i.Specialty,
			&i.Biography,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHealer = `-- name: UpdateHealer :one
UPDATE healer
SET district_id = $2, full_name = $3, sub_district = $4, specialty = $5, biography = $6, updated_at = now()
WHERE id = $1
RETURNING id, district_id, full_name, sub_district, specialty, biography, created_at, updated_at
`

type UpdateHealerParams struct {
	ID          int64
	DistrictID  int64
	FullName    string
	SubDistrict string
	Specialty   string
	Biography   string
}

func (q *Queries) UpdateHealer(ctx context.Context, arg UpdateHealerParams) (Healer, error) {
	row := q.db.QueryRow(ctx, updateHealer,
		arg.ID,
		arg.DistrictID,
		arg.FullName,
		arg.SubDistrict,
		arg.Specialty,
		arg.Biography,
	)
	var i Healer
	err := row.Scan(
		&i.ID,
		&i.DistrictID,
		&i.FullName,
		&i.SubDistrict,
		&i.Specialty,
		&i.Biography,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
