// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: herb.sql

package db

import (
	"context"
)

const createHerb = `-- name: CreateHerb :one
INSERT INTO herb (name_thai, name_english, scientific_name, properties, description)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name_thai, name_english, scientific_name, properties, description, created_at, updated_at
`

type CreateHerbParams struct {
	NameThai       string
	NameEnglish    string
	ScientificName string
	Properties     string
	Description    string
}

func (q *Queries) CreateHerb(ctx context.Context, arg CreateHerbParams) (Herb, error) {
	row := q.db.QueryRow(ctx, createHerb,
		arg.NameThai,
		arg.NameEnglish,
		arg.ScientificName,
		arg.Properties,
		arg.Description,
	)
	var i Herb
	err := row.Scan(
		&i.ID,
		&i.NameThai,
		&i.NameEnglish,
		&i.ScientificName,
		&i.Properties,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteHerb = `-- name: DeleteHerb :execrows
DELETE FROM herb WHERE id = $1
`

func (q *Queries) DeleteHerb(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteHerb, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getHerb = `-- name: GetHerb :one
SELECT id, name_thai, name_english, scientific_name, properties, description, created_at, updated_at
FROM herb
WHERE id = $1
`

func (q *Queries) GetHerb(ctx context.Context, id int64) (Herb, error) {
	row := q.db.QueryRow(ctx, getHerb, id)
	var i Herb
	err := row.Scan(
		&i.ID,
		&i.NameThai,
		&i.NameEnglish,
		&i.ScientificName,
		&i.Properties,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listHerb = `-- name: ListHerb :many
SELECT id, name_thai, name_english, scientific_name, properties, description, created_at, updated_at
FROM herb
ORDER BY name_thai
`

func (q *Queries) ListHerb(ctx context.Context) ([]Herb, error) {
	rows, err := q.db.Query(ctx, listHerb)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Herb{}
	for rows.Next() {
		var i Herb
		if err := rows.Scan(
			&i.ID,
			&i.NameThai,
			&i.NameEnglish,
			&i.ScientificName,
			&i.Properties,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchHerb = `-- name: SearchHerb :many
SELECT id, name_thai, name_english, scientific_name, properties, description, created_at, updated_at
FROM herb
WHERE name_thai ILIKE '%' || $1::text || '%'
   OR name_english ILIKE '%' || $1::text || '%'
   OR scientific_name ILIKE '%' || $1::text || '%'
   OR properties ILIKE '%' || $1::text || '%'
ORDER BY GREATEST(
    similarity(name_thai, $1::text),
    similarity(name_english, $1::text)
) DESC, name_thai
`

func (q *Queries) SearchHerb(ctx context.Context, searchTerm string) ([]Herb, error) {
	rows, err := q.db.Query(ctx, searchHerb, searchTerm)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Herb{}
	for rows.Next() {
		var i Herb
		if err := rows.Scan(
			&i.ID,
			&i.NameThai,
			&i.NameEnglish,
			&i.ScientificName,
			&i.Properties,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHerb = `-- name: UpdateHerb :one
UPDATE herb
SET name_thai = $2, name_english = $3, scientific_name = $4, properties = $5, description = $6, updated_at = now()
WHERE id = $1
RETURNING id, name_thai, name_english, scientific_name, properties, description, created_at, updated_at
`

type UpdateHerbParams struct {
	ID             int64
	NameThai       string
	NameEnglish    string
	ScientificName string
	Properties     string
	Description    string
}

func (q *Queries) UpdateHerb(ctx context.Context, arg UpdateHerbParams) (Herb, error) {
	row := q.db.QueryRow(ctx, updateHerb,
		arg.ID,
		arg.NameThai,
		arg.NameEnglish,
		arg.ScientificName,
		arg.Properties,
		arg.Description,
	)
	var i Herb
	err := row.Scan(
		&i.ID,
		&i.NameThai,
		&i.NameEnglish,
		&i.ScientificName,
		&i.Properties,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
