// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: herb.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countHerbPage = `-- name: CountHerbPage :one
SELECT COUNT(*) FROM herb
WHERE ($1::text IS NULL OR name_thai ILIKE '%'||$1||'%' OR name_english ILIKE '%'||$1||'%' OR scientific_name ILIKE '%'||$1||'%')
`

func (q *Queries) CountHerbPage(ctx context.Context, searchTerm pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countHerbPage, searchTerm)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createHerb = `-- name: CreateHerb :one
INSERT INTO herb (name_thai, name_english, scientific_name, properties, description)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name_thai, name_english, scientific_name, properties, description, created_at, updated_at
`

type CreateHerbParams struct {
	NameThai       string
	NameEnglish    string
	ScientificName string
	Properties     string
	Description    string
}

func (q *Queries) CreateHerb(ctx context.Context, arg CreateHerbParams) (Herb, error) {
	row := q.db.QueryRow(ctx, createHerb,
		arg.NameThai,
		arg.NameEnglish,
		arg.ScientificName,
		arg.Properties,
		arg.Description,
	)
	var i Herb
	err := row.Scan(
		&i.ID,
		&i.NameThai,
		&i.NameEnglish,
		&i.ScientificName,
		&i.Properties,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteHerb = `-- name: DeleteHerb :execrows
DELETE FROM herb WHERE id = $1
`

func (q *Queries) DeleteHerb(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteHerb, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getHerb = `-- name: GetHerb :one
SELECT id, name_thai, name_english, scientific_name, properties, description, created_at, updated_at
FROM herb
WHERE id = $1
`

func (q *Queries) GetHerb(ctx context.Context, id int64) (Herb, error) {
	row := q.db.QueryRow(ctx, getHerb, id)
	var i Herb
	err := row.Scan(
		&i.ID,
		&i.NameThai,
		&i.NameEnglish,
		&i.ScientificName,
		&i.Properties,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listHerbPage = `-- name: ListHerbPage :many
SELECT id, name_thai, name_english, scientific_name, properties, description, created_at, updated_at
FROM herb
WHERE ($1::text IS NULL OR name_thai ILIKE '%'||$1||'%' OR name_english ILIKE '%'||$1||'%' OR scientific_name ILIKE '%'||$1||'%')
ORDER BY name_thai
LIMIT $3 OFFSET $2
`

type ListHerbPageParams struct {
	SearchTerm pgtype.Text
	PageOffset int32
	PageLimit  int32
}

func (q *Queries) ListHerbPage(ctx context.Context, arg ListHerbPageParams) ([]Herb, error) {
	rows, err := q.db.Query(ctx, listHerbPage, arg.SearchTerm, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Herb{}
	for rows.Next() {
		var i Herb
		if err := rows.Scan(
			&i.ID,
			&i.NameThai,
			&i.NameEnglish,
			&i.ScientificName,
			&i.Properties,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHerb = `-- name: UpdateHerb :one
UPDATE herb
SET name_thai = $2, name_english = $3, scientific_name = $4, properties = $5, description = $6, updated_at = now()
WHERE id = $1
RETURNING id, name_thai, name_english, scientific_name, properties, description, created_at, updated_at
`

type UpdateHerbParams struct {
	ID             int64
	NameThai       string
	NameEnglish    string
	ScientificName string
	Properties     string
	Description    string
}

func (q *Queries) UpdateHerb(ctx context.Context, arg UpdateHerbParams) (Herb, error) {
	row := q.db.QueryRow(ctx, updateHerb,
		arg.ID,
		arg.NameThai,
		arg.NameEnglish,
		arg.ScientificName,
		arg.Properties,
		arg.Description,
	)
	var i Herb
	err := row.Scan(
		&i.ID,
		&i.NameThai,
		&i.NameEnglish,
		&i.ScientificName,
		&i.Properties,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
