// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: location.sql

package db

import (
	"context"
)

const countDistrictByProvince = `-- name: CountDistrictByProvince :one
SELECT COUNT(*) FROM district WHERE province_id = $1
`

func (q *Queries) CountDistrictByProvince(ctx context.Context, provinceID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countDistrictByProvince, provinceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDistrict = `-- name: CreateDistrict :one
INSERT INTO district (province_id, name_thai, name_english)
VALUES ($1, $2, $3)
RETURNING id, province_id, name_thai, name_english
`

type CreateDistrictParams struct {
	ProvinceID  int64
	NameThai    string
	NameEnglish string
}

func (q *Queries) CreateDistrict(ctx context.Context, arg CreateDistrictParams) (District, error) {
	row := q.db.QueryRow(ctx, createDistrict, arg.ProvinceID, arg.NameThai, arg.NameEnglish)
	var i District
	err := row.Scan(
		&i.ID,
		&i.ProvinceID,
		&i.NameThai,
		&i.NameEnglish,
	)
	return i, err
}

const createProvince = `-- name: CreateProvince :one
INSERT INTO province (name_thai, name_english)
VALUES ($1, $2)
RETURNING id, name_thai, name_english
`

type CreateProvinceParams struct {
	NameThai    string
	NameEnglish string
}

func (q *Queries) CreateProvince(ctx context.Context, arg CreateProvinceParams) (Province, error) {
	row := q.db.QueryRow(ctx, createProvince, arg.NameThai, arg.NameEnglish)
	var i Province
	err := row.Scan(&i.ID, &i.NameThai, &i.NameEnglish)
	return i, err
}

const deleteDistrict = `-- name: DeleteDistrict :execrows
DELETE FROM district WHERE id = $1
`

func (q *Queries) DeleteDistrict(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDistrict, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProvince = `-- name: DeleteProvince :execrows
DELETE FROM province WHERE id = $1
`

func (q *Queries) DeleteProvince(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProvince, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDistrict = `-- name: GetDistrict :one
SELECT id, province_id, name_thai, name_english
FROM district
WHERE id = $1
`

func (q *Queries) GetDistrict(ctx context.Context, id int64) (District, error) {
	row := q.db.QueryRow(ctx, getDistrict, id)
	var i District
	err := row.Scan(
		&i.ID,
		&i.ProvinceID,
		&i.NameThai,
		&i.NameEnglish,
	)
	return i, err
}

const getProvince = `-- name: GetProvince :one
SELECT id, name_thai, name_english
FROM province
WHERE id = $1
`

func (q *Queries) GetProvince(ctx context.Context, id int64) (Province, error) {
	row := q.db.QueryRow(ctx, getProvince, id)
	var i Province
	err := row.Scan(&i.ID, &i.NameThai, &i.NameEnglish)
	return i, err
}

const listDistrictByProvince = `-- name: ListDistrictByProvince :many
SELECT id, province_id, name_thai, name_english
FROM district
WHERE province_id = $1
ORDER BY name_english
`

func (q *Queries) ListDistrictByProvince(ctx context.Context, provinceID int64) ([]District, error) {
	rows, err := q.db.Query(ctx, listDistrictByProvince, provinceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []District{}
	for rows.Next() {
		var i District
		if err := rows.Scan(
			&i.ID,
			&i.ProvinceID,
			&i.NameThai,
			&i.NameEnglish,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProvince = `-- name: ListProvince :many
SELECT id, name_thai, name_english
FROM province
ORDER BY name_english
`

func (q *Queries) ListProvince(ctx context.Context) ([]Province, error) {
	rows, err := q.db.Query(ctx, listProvince)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Province{}
	for rows.Next() {
		var i Province
		if err := rows.Scan(&i.ID, &i.NameThai, &i.NameEnglish); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDistrict = `-- name: UpdateDistrict :one
UPDATE district
SET name_thai = $2, name_english = $3
WHERE id = $1
RETURNING id, province_id, name_thai, name_english
`

type UpdateDistrictParams struct {
	ID          int64
	NameThai    string
	NameEnglish string
}

func (q *Queries) UpdateDistrict(ctx context.Context, arg UpdateDistrictParams) (District, error) {
	row := q.db.QueryRow(ctx, updateDistrict, arg.ID, arg.NameThai, arg.NameEnglish)
	var i District
	err := row.Scan(
		&i.ID,
		&i.ProvinceID,
		&i.NameThai,
		&i.NameEnglish,
	)
	return i, err
}

const updateProvince = `-- name: UpdateProvince :one
UPDATE province
SET name_thai = $2, name_english = $3
WHERE id = $1
RETURNING id, name_thai, name_english
`

type UpdateProvinceParams struct {
	ID          int64
	NameThai    string
	NameEnglish string
}

func (q *Queries) UpdateProvince(ctx context.Context, arg UpdateProvinceParams) (Province, error) {
	row := q.db.QueryRow(ctx, updateProvince, arg.ID, arg.NameThai, arg.NameEnglish)
	var i Province
	err := row.Scan(&i.ID, &i.NameThai, &i.NameEnglish)
	return i, err
}
