// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: location.sql

package db

import (
	"context"
)

const getDistrict = `-- name: GetDistrict :one
SELECT id, province_id, name_thai, name_english
FROM district
WHERE id = $1
`

func (q *Queries) GetDistrict(ctx context.Context, id int64) (District, error) {
	row := q.db.QueryRow(ctx, getDistrict, id)
	var i District
	err := row.Scan(
		&i.ID,
		&i.ProvinceID,
		&i.NameThai,
		&i.NameEnglish,
	)
	return i, err
}

const listDistrictByProvince = `-- name: ListDistrictByProvince :many
SELECT id, province_id, name_thai, name_english
FROM district
WHERE province_id = $1
ORDER BY name_english
`

func (q *Queries) ListDistrictByProvince(ctx context.Context, provinceID int64) ([]District, error) {
	rows, err := q.db.Query(ctx, listDistrictByProvince, provinceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []District{}
	for rows.Next() {
		var i District
		if err := rows.Scan(
			&i.ID,
			&i.ProvinceID,
			&i.NameThai,
			&i.NameEnglish,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProvince = `-- name: ListProvince :many
SELECT id, name_thai, name_english
FROM province
ORDER BY name_english
`

func (q *Queries) ListProvince(ctx context.Context) ([]Province, error) {
	rows, err := q.db.Query(ctx, listProvince)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Province{}
	for rows.Next() {
		var i Province
		if err := rows.Scan(&i.ID, &i.NameThai, &i.NameEnglish); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
