// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type District struct {
	ID          int64
	ProvinceID  int64
	NameThai    string
	NameEnglish string
}

type Healer struct {
	ID          int64
	DistrictID  int64
	FullName    string
	SubDistrict string
	Specialty   string
	Biography   string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Province struct {
	ID          int64
	NameThai    string
	NameEnglish string
}

type Remedy struct {
	ID                int64
	HealerID          int64
	Name              string
	Symptoms          string
	Ingredients       string
	PreparationMethod string
	Usage             string
	Note              string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}
