// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type District struct {
	ID          int64
	ProvinceID  int64
	NameThai    string
	NameEnglish string
}

type Province struct {
	ID          int64
	NameThai    string
	NameEnglish string
}
