// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: photo.sql

package db

import (
	"context"
)

const createPhoto = `-- name: CreatePhoto :one
INSERT INTO photo (owner_type, owner_id, object_key, caption)
VALUES ($1, $2, $3, $4)
RETURNING id, owner_type, owner_id, object_key, caption, created_at
`

type CreatePhotoParams struct {
	OwnerType string
	OwnerID   int64
	ObjectKey string
	Caption   string
}

func (q *Queries) CreatePhoto(ctx context.Context, arg CreatePhotoParams) (Photo, error) {
	row := q.db.QueryRow(ctx, createPhoto,
		arg.OwnerType,
		arg.OwnerID,
		arg.ObjectKey,
		arg.Caption,
	)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.OwnerType,
		&i.OwnerID,
		&i.ObjectKey,
		&i.Caption,
		&i.CreatedAt,
	)
	return i, err
}

const deletePhoto = `-- name: DeletePhoto :execrows
DELETE FROM photo WHERE id = $1
`

func (q *Queries) DeletePhoto(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deletePhoto, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPhoto = `-- name: GetPhoto :one
SELECT id, owner_type, owner_id, object_key, caption, created_at
FROM photo
WHERE id = $1
`

func (q *Queries) GetPhoto(ctx context.Context, id int64) (Photo, error) {
	row := q.db.QueryRow(ctx, getPhoto, id)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.OwnerType,
		&i.OwnerID,
		&i.ObjectKey,
		&i.Caption,
		&i.CreatedAt,
	)
	return i, err
}
