// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: remedy.sql

package db

import (
	"context"
)

const countRemedyByHealer = `-- name: CountRemedyByHealer :one
SELECT COUNT(*) FROM remedy WHERE healer_id = $1
`

func (q *Queries) CountRemedyByHealer(ctx context.Context, healerID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countRemedyByHealer, healerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRemedyPage = `-- name: CountRemedyPage :one
SELECT COUNT(*) FROM remedy
`

func (q *Queries) CountRemedyPage(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRemedyPage)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRemedy = `-- name: CreateRemedy :one
INSERT INTO remedy (healer_id, name, symptoms, preparation_method, usage, note)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, healer_id, name, symptoms, preparation_method, usage, note, created_at, updated_at
`

type CreateRemedyParams struct {
	HealerID          int64
	Name              string
	Symptoms          string
	PreparationMethod string
	Usage             string
	Note              string
}

func (q *Queries) CreateRemedy(ctx context.Context, arg CreateRemedyParams) (Remedy, error) {
	row := q.db.QueryRow(ctx, createRemedy,
		arg.HealerID,
		arg.Name,
		arg.Symptoms,
		arg.PreparationMethod,
		arg.Usage,
		arg.Note,
	)
	var i Remedy
	err := row.Scan(
		&i.ID,
		&i.HealerID,
		&i.Name,
		&i.Symptoms,
		&i.PreparationMethod,
		&i.Usage,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRemedy = `-- name: DeleteRemedy :execrows
DELETE FROM remedy WHERE id = $1
`

func (q *Queries) DeleteRemedy(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRemedy, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRemedy = `-- name: GetRemedy :one
SELECT id, healer_id, name, symptoms, preparation_method, usage, note, created_at, updated_at
FROM remedy
WHERE id = $1
`

func (q *Queries) GetRemedy(ctx context.Context, id int64) (Remedy, error) {
	row := q.db.QueryRow(ctx, getRemedy, id)
	var i Remedy
	err := row.Scan(
		&i.ID,
		&i.HealerID,
		&i.Name,
		&i.Symptoms,
		&i.PreparationMethod,
		&i.Usage,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRemedyByHealerPage = `-- name: ListRemedyByHealerPage :many
SELECT id, healer_id, name, symptoms, preparation_method, usage, note, created_at, updated_at
FROM remedy
WHERE healer_id = $1
ORDER BY name
LIMIT $3 OFFSET $2
`

type ListRemedyByHealerPageParams struct {
	HealerID   int64
	PageOffset int32
	PageLimit  int32
}

func (q *Queries) ListRemedyByHealerPage(ctx context.Context, arg ListRemedyByHealerPageParams) ([]Remedy, error) {
	rows, err := q.db.Query(ctx, listRemedyByHealerPage, arg.HealerID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Remedy{}
	for rows.Next() {
		var i Remedy
		if err := rows.Scan(
			&i.ID,
			&i.HealerID,
			&i.Name,
			&i.Symptoms,
			&i.PreparationMethod,
			&i.Usage,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRemedyPage = `-- name: ListRemedyPage :many
SELECT id, healer_id, name, symptoms, preparation_method, usage, note, created_at, updated_at
FROM remedy
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $1
`

type ListRemedyPageParams struct {
	PageOffset int32
	PageLimit  int32
}

func (q *Queries) ListRemedyPage(ctx context.Context, arg ListRemedyPageParams) ([]Remedy, error) {
	rows, err := q.db.Query(ctx, listRemedyPage, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Remedy{}
	for rows.Next() {
		var i Remedy
		if err := rows.Scan(
			&i.ID,
			&i.HealerID,
			&i.Name,
			&i.Symptoms,
			&i.PreparationMethod,
			&i.Usage,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRemedy = `-- name: UpdateRemedy :one
UPDATE remedy
SET name = $2, symptoms = $3, preparation_method = $4, usage = $5, note = $6, updated_at = now()
WHERE id = $1
RETURNING id, healer_id, name, symptoms, preparation_method, usage, note, created_at, updated_at
`

type UpdateRemedyParams struct {
	ID                int64
	Name              string
	Symptoms          string
	PreparationMethod string
	Usage             string
	Note              string
}

func (q *Queries) UpdateRemedy(ctx context.Context, arg UpdateRemedyParams) (Remedy, error) {
	row := q.db.QueryRow(ctx, updateRemedy,
		arg.ID,
		arg.Name,
		arg.Symptoms,
		arg.PreparationMethod,
		arg.Usage,
		arg.Note,
	)
	var i Remedy
	err := row.Scan(
		&i.ID,
		&i.HealerID,
		&i.Name,
		&i.Symptoms,
		&i.PreparationMethod,
		&i.Usage,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
