// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: remedy_herb.sql

package db

import (
	"context"
)

const countRemedyByHerb = `-- name: CountRemedyByHerb :one
SELECT COUNT(*)
FROM remedy r
JOIN remedy_herb rh ON rh.remedy_id = r.id
WHERE rh.herb_id = $1
`

func (q *Queries) CountRemedyByHerb(ctx context.Context, herbID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countRemedyByHerb, herbID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteRemedyHerbByRemedy = `-- name: DeleteRemedyHerbByRemedy :exec
DELETE FROM remedy_herb WHERE remedy_id = $1
`

func (q *Queries) DeleteRemedyHerbByRemedy(ctx context.Context, remedyID int64) error {
	_, err := q.db.Exec(ctx, deleteRemedyHerbByRemedy, remedyID)
	return err
}

const insertRemedyHerb = `-- name: InsertRemedyHerb :exec
INSERT INTO remedy_herb (remedy_id, herb_id, amount, position)
VALUES ($1, $2, $3, $4)
`

type InsertRemedyHerbParams struct {
	RemedyID int64
	HerbID   int64
	Amount   string
	Position int32
}

func (q *Queries) InsertRemedyHerb(ctx context.Context, arg InsertRemedyHerbParams) error {
	_, err := q.db.Exec(ctx, insertRemedyHerb,
		arg.RemedyID,
		arg.HerbID,
		arg.Amount,
		arg.Position,
	)
	return err
}

const listHerbByRemedy = `-- name: ListHerbByRemedy :many
SELECT rh.herb_id, h.name_thai, h.name_english, rh.amount
FROM remedy_herb rh
JOIN herb h ON h.id = rh.herb_id
WHERE rh.remedy_id = $1
ORDER BY rh.position, h.name_thai
`

type ListHerbByRemedyRow struct {
	HerbID      int64
	NameThai    string
	NameEnglish string
	Amount      string
}

func (q *Queries) ListHerbByRemedy(ctx context.Context, remedyID int64) ([]ListHerbByRemedyRow, error) {
	rows, err := q.db.Query(ctx, listHerbByRemedy, remedyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHerbByRemedyRow{}
	for rows.Next() {
		var i ListHerbByRemedyRow
		if err := rows.Scan(
			&i.HerbID,
			&i.NameThai,
			&i.NameEnglish,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRemedyByHerbPage = `-- name: ListRemedyByHerbPage :many
SELECT r.id, r.healer_id, r.name, r.symptoms, r.preparation_method, r.usage, r.note, r.created_at, r.updated_at
FROM remedy r
JOIN remedy_herb rh ON rh.remedy_id = r.id
WHERE rh.herb_id = $1
ORDER BY r.name
LIMIT $3 OFFSET $2
`

type ListRemedyByHerbPageParams struct {
	HerbID     int64
	PageOffset int32
	PageLimit  int32
}

func (q *Queries) ListRemedyByHerbPage(ctx context.Context, arg ListRemedyByHerbPageParams) ([]Remedy, error) {
	rows, err := q.db.Query(ctx, listRemedyByHerbPage, arg.HerbID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Remedy{}
	for rows.Next() {
		var i Remedy
		if err := rows.Scan(
			&i.ID,
			&i.HealerID,
			&i.Name,
			&i.Symptoms,
			&i.PreparationMethod,
			&i.Usage,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
