// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: remedy.sql

package db

import (
	"context"
)

const createRemedy = `-- name: CreateRemedy :one
INSERT INTO remedy (healer_id, name, symptoms, preparation_method, usage, note)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, healer_id, name, symptoms, preparation_method, usage, note, created_at, updated_at
`

type CreateRemedyParams struct {
	HealerID          int64
	Name              string
	Symptoms          string
	PreparationMethod string
	Usage             string
	Note              string
}

func (q *Queries) CreateRemedy(ctx context.Context, arg CreateRemedyParams) (Remedy, error) {
	row := q.db.QueryRow(ctx, createRemedy,
		arg.HealerID,
		arg.Name,
		arg.Symptoms,
		arg.PreparationMethod,
		arg.Usage,
		arg.Note,
	)
	var i Remedy
	err := row.Scan(
		&i.ID,
		&i.HealerID,
		&i.Name,
		&i.Symptoms,
		&i.PreparationMethod,
		&i.Usage,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRemedy = `-- name: DeleteRemedy :execrows
DELETE FROM remedy WHERE id = $1
`

func (q *Queries) DeleteRemedy(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRemedy, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRemedy = `-- name: GetRemedy :one
SELECT id, healer_id, name, symptoms, preparation_method, usage, note, created_at, updated_at
FROM remedy
WHERE id = $1
`

func (q *Queries) GetRemedy(ctx context.Context, id int64) (Remedy, error) {
	row := q.db.QueryRow(ctx, getRemedy, id)
	var i Remedy
	err := row.Scan(
		&i.ID,
		&i.HealerID,
		&i.Name,
		&i.Symptoms,
		&i.PreparationMethod,
		&i.Usage,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRecentRemedy = `-- name: ListRecentRemedy :many
SELECT id, healer_id, name, symptoms, preparation_method, usage, note, created_at, updated_at
FROM remedy
ORDER BY created_at DESC, id DESC
LIMIT $1
`

func (q *Queries) ListRecentRemedy(ctx context.Context, limit int32) ([]Remedy, error) {
	rows, err := q.db.Query(ctx, listRecentRemedy, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Remedy{}
	for rows.Next() {
		var i Remedy
		if err := rows.Scan(
			&i.ID,
			&i.HealerID,
			&i.Name,
			&i.Symptoms,
			&i.PreparationMethod,
			&i.Usage,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRemedyByHealer = `-- name: ListRemedyByHealer :many
SELECT id, healer_id, name, symptoms, preparation_method, usage, note, created_at, updated_at
FROM remedy
WHERE healer_id = $1
ORDER BY name
`

func (q *Queries) ListRemedyByHealer(ctx context.Context, healerID int64) ([]Remedy, error) {
	rows, err := q.db.Query(ctx, listRemedyByHealer, healerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Remedy{}
	for rows.Next() {
		var i Remedy
		if err := rows.Scan(
			&i.ID,
			&i.HealerID,
			&i.Name,
			&i.Symptoms,
			&i.PreparationMethod,
			&i.Usage,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchRemedy = `-- name: SearchRemedy :many
SELECT DISTINCT r.id, r.name, r.symptoms, r.healer_id, h.full_name AS healer_full_name
FROM remedy r
JOIN healer h ON h.id = r.healer_id
LEFT JOIN remedy_herb rh ON rh.remedy_id = r.id
LEFT JOIN herb hb ON hb.id = rh.herb_id
WHERE r.name ILIKE '%' || $1::text || '%'
   OR r.symptoms ILIKE '%' || $1::text || '%'
   OR hb.name_thai ILIKE '%' || $1::text || '%'
   OR hb.name_english ILIKE '%' || $1::text || '%'
ORDER BY r.name
`

type SearchRemedyRow struct {
	ID             int64
	Name           string
	Symptoms       string
	HealerID       int64
	HealerFullName string
}

func (q *Queries) SearchRemedy(ctx context.Context, searchTerm string) ([]SearchRemedyRow, error) {
	rows, err := q.db.Query(ctx, searchRemedy, searchTerm)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchRemedyRow{}
	for rows.Next() {
		var i SearchRemedyRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Symptoms,
			&i.HealerID,
			&i.HealerFullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRemedy = `-- name: UpdateRemedy :one
UPDATE remedy
SET name = $2, symptoms = $3, preparation_method = $4, usage = $5, note = $6, updated_at = now()
WHERE id = $1
RETURNING id, healer_id, name, symptoms, preparation_method, usage, note, created_at, updated_at
`

type UpdateRemedyParams struct {
	ID                int64
	Name              string
	Symptoms          string
	PreparationMethod string
	Usage             string
	Note              string
}

func (q *Queries) UpdateRemedy(ctx context.Context, arg UpdateRemedyParams) (Remedy, error) {
	row := q.db.QueryRow(ctx, updateRemedy,
		arg.ID,
		arg.Name,
		arg.Symptoms,
		arg.PreparationMethod,
		arg.Usage,
		arg.Note,
	)
	var i Remedy
	err := row.Scan(
		&i.ID,
		&i.HealerID,
		&i.Name,
		&i.Symptoms,
		&i.PreparationMethod,
		&i.Usage,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
