// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: remedy.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRemedyPage = `-- name: CountRemedyPage :one
SELECT COUNT(*)
FROM remedy r
JOIN healer h ON h.id = r.healer_id
WHERE ($1::bigint IS NULL
       OR EXISTS (SELECT 1 FROM remedy_herb rh
                  WHERE rh.remedy_id = r.id AND rh.herb_id = $1::bigint))
  AND ($2::bigint IS NULL OR h.district_id = $2::bigint)
  AND ($3::text IS NULL OR r.symptoms ILIKE '%' || $3::text || '%')
`

type CountRemedyPageParams struct {
	HerbID     pgtype.Int8
	DistrictID pgtype.Int8
	Symptom    pgtype.Text
}

func (q *Queries) CountRemedyPage(ctx context.Context, arg CountRemedyPageParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRemedyPage, arg.HerbID, arg.DistrictID, arg.Symptom)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRemedy = `-- name: CreateRemedy :one
INSERT INTO remedy (healer_id, name, symptoms, preparation_method, usage, note)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, healer_id, name, symptoms, preparation_method, usage, note, created_at, updated_at
`

type CreateRemedyParams struct {
	HealerID          int64
	Name              string
	Symptoms          string
	PreparationMethod string
	Usage             string
	Note              string
}

func (q *Queries) CreateRemedy(ctx context.Context, arg CreateRemedyParams) (Remedy, error) {
	row := q.db.QueryRow(ctx, createRemedy,
		arg.HealerID,
		arg.Name,
		arg.Symptoms,
		arg.PreparationMethod,
		arg.Usage,
		arg.Note,
	)
	var i Remedy
	err := row.Scan(
		&i.ID,
		&i.HealerID,
		&i.Name,
		&i.Symptoms,
		&i.PreparationMethod,
		&i.Usage,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRemedy = `-- name: DeleteRemedy :execrows
DELETE FROM remedy WHERE id = $1
`

func (q *Queries) DeleteRemedy(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRemedy, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRemedy = `-- name: GetRemedy :one
SELECT id, healer_id, name, symptoms, preparation_method, usage, note, created_at, updated_at
FROM remedy
WHERE id = $1
`

func (q *Queries) GetRemedy(ctx context.Context, id int64) (Remedy, error) {
	row := q.db.QueryRow(ctx, getRemedy, id)
	var i Remedy
	err := row.Scan(
		&i.ID,
		&i.HealerID,
		&i.Name,
		&i.Symptoms,
		&i.PreparationMethod,
		&i.Usage,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRemedyByHealer = `-- name: ListRemedyByHealer :many
SELECT id, healer_id, name, symptoms, preparation_method, usage, note, created_at, updated_at
FROM remedy
WHERE healer_id = $1
ORDER BY name
`

func (q *Queries) ListRemedyByHealer(ctx context.Context, healerID int64) ([]Remedy, error) {
	rows, err := q.db.Query(ctx, listRemedyByHealer, healerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Remedy{}
	for rows.Next() {
		var i Remedy
		if err := rows.Scan(
			&i.ID,
			&i.HealerID,
			&i.Name,
			&i.Symptoms,
			&i.PreparationMethod,
			&i.Usage,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRemedyPage = `-- name: ListRemedyPage :many
SELECT r.id, r.healer_id, r.name, r.symptoms, r.preparation_method, r.usage, r.note, r.created_at, r.updated_at
FROM remedy r
JOIN healer h ON h.id = r.healer_id
WHERE ($1::bigint IS NULL
       OR EXISTS (SELECT 1 FROM remedy_herb rh
                  WHERE rh.remedy_id = r.id AND rh.herb_id = $1::bigint))
  AND ($2::bigint IS NULL OR h.district_id = $2::bigint)
  AND ($3::text IS NULL OR r.symptoms ILIKE '%' || $3::text || '%')
ORDER BY r.created_at DESC, r.id DESC
LIMIT $5 OFFSET $4
`

type ListRemedyPageParams struct {
	HerbID     pgtype.Int8
	DistrictID pgtype.Int8
	Symptom    pgtype.Text
	PageOffset int32
	PageLimit  int32
}

func (q *Queries) ListRemedyPage(ctx context.Context, arg ListRemedyPageParams) ([]Remedy, error) {
	rows, err := q.db.Query(ctx, listRemedyPage,
		arg.HerbID,
		arg.DistrictID,
		arg.Symptom,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Remedy{}
	for rows.Next() {
		var i Remedy
		if err := rows.Scan(
			&i.ID,
			&i.HealerID,
			&i.Name,
			&i.Symptoms,
			&i.PreparationMethod,
			&i.Usage,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchRemedy = `-- name: SearchRemedy :many
SELECT r.id, r.name, r.symptoms, r.healer_id, h.full_name AS healer_full_name
FROM remedy r
JOIN healer h ON h.id = r.healer_id
LEFT JOIN remedy_herb rh ON rh.remedy_id = r.id
LEFT JOIN herb hb ON hb.id = rh.herb_id
WHERE r.name ILIKE '%' || $1::text || '%'
   OR r.symptoms ILIKE '%' || $1::text || '%'
   OR hb.name_thai ILIKE '%' || $1::text || '%'
   OR hb.name_english ILIKE '%' || $1::text || '%'
GROUP BY r.id, r.name, r.symptoms, r.healer_id, h.full_name
ORDER BY GREATEST(
    similarity(r.name, $1::text),
    similarity(r.symptoms, $1::text),
    max(similarity(hb.name_thai, $1::text)),
    max(similarity(hb.name_english, $1::text))
) DESC, r.name
`

type SearchRemedyRow struct {
	ID             int64
	Name           string
	Symptoms       string
	HealerID       int64
	HealerFullName string
}

func (q *Queries) SearchRemedy(ctx context.Context, searchTerm string) ([]SearchRemedyRow, error) {
	rows, err := q.db.Query(ctx, searchRemedy, searchTerm)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchRemedyRow{}
	for rows.Next() {
		var i SearchRemedyRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Symptoms,
			&i.HealerID,
			&i.HealerFullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRemedy = `-- name: UpdateRemedy :one
UPDATE remedy
SET name = $2, symptoms = $3, preparation_method = $4, usage = $5, note = $6, updated_at = now()
WHERE id = $1
RETURNING id, healer_id, name, symptoms, preparation_method, usage, note, created_at, updated_at
`

type UpdateRemedyParams struct {
	ID                int64
	Name              string
	Symptoms          string
	PreparationMethod string
	Usage             string
	Note              string
}

func (q *Queries) UpdateRemedy(ctx context.Context, arg UpdateRemedyParams) (Remedy, error) {
	row := q.db.QueryRow(ctx, updateRemedy,
		arg.ID,
		arg.Name,
		arg.Symptoms,
		arg.PreparationMethod,
		arg.Usage,
		arg.Note,
	)
	var i Remedy
	err := row.Scan(
		&i.ID,
		&i.HealerID,
		&i.Name,
		&i.Symptoms,
		&i.PreparationMethod,
		&i.Usage,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
