// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package db

import (
	"context"
)

const countSearchAll = `-- name: CountSearchAll :one
WITH hits AS (
  SELECT 'remedy'::text AS type, r.id,
         GREATEST(similarity(r.name, $1::text), similarity(r.symptoms, $1::text),
                  COALESCE(max(similarity(hb.name_thai, $1::text)), 0))::real AS score
  FROM remedy r
  LEFT JOIN remedy_herb rh ON rh.remedy_id = r.id
  LEFT JOIN herb hb ON hb.id = rh.herb_id
  GROUP BY r.id, r.name, r.symptoms
  UNION ALL
  SELECT 'healer'::text, h.id,
         GREATEST(similarity(h.full_name, $1::text), similarity(h.specialty, $1::text))::real
  FROM healer h
  UNION ALL
  SELECT 'herb'::text, hb.id,
         GREATEST(similarity(hb.name_thai, $1::text), similarity(hb.name_english, $1::text),
                  similarity(hb.scientific_name, $1::text))::real
  FROM herb hb
)
SELECT COUNT(*) FROM hits WHERE score > 0
`

func (q *Queries) CountSearchAll(ctx context.Context, searchTerm string) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchAll, searchTerm)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const searchAll = `-- name: SearchAll :many
WITH hits AS (
  SELECT 'remedy'::text AS type, r.id, r.name AS title, r.symptoms AS subtitle,
         GREATEST(similarity(r.name, $3::text), similarity(r.symptoms, $3::text),
                  COALESCE(max(similarity(hb.name_thai, $3::text)), 0))::real AS score
  FROM remedy r
  LEFT JOIN remedy_herb rh ON rh.remedy_id = r.id
  LEFT JOIN herb hb ON hb.id = rh.herb_id
  GROUP BY r.id, r.name, r.symptoms
  UNION ALL
  SELECT 'healer'::text, h.id, h.full_name, h.sub_district,
         GREATEST(similarity(h.full_name, $3::text), similarity(h.specialty, $3::text))::real
  FROM healer h
  UNION ALL
  SELECT 'herb'::text, hb.id, hb.name_thai, hb.name_english,
         GREATEST(similarity(hb.name_thai, $3::text), similarity(hb.name_english, $3::text),
                  similarity(hb.scientific_name, $3::text))::real
  FROM herb hb
)
SELECT type, id, title, subtitle, score FROM hits
WHERE score > 0
ORDER BY score DESC, type, id
LIMIT $2 OFFSET $1
`

type SearchAllParams struct {
	PageOffset int32
	PageLimit  int32
	SearchTerm string
}

type SearchAllRow struct {
	Type     string
	ID       int64
	Title    string
	Subtitle string
	Score    float32
}

func (q *Queries) SearchAll(ctx context.Context, arg SearchAllParams) ([]SearchAllRow, error) {
	rows, err := q.db.Query(ctx, searchAll, arg.PageOffset, arg.PageLimit, arg.SearchTerm)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchAllRow{}
	for rows.Next() {
		var i SearchAllRow
		if err := rows.Scan(
			&i.Type,
			&i.ID,
			&i.Title,
			&i.Subtitle,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
