// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: staff.sql

package db

import (
	"context"
)

const countStaff = `-- name: CountStaff :one
SELECT count(*) FROM staff_user
`

func (q *Queries) CountStaff(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countStaff)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createStaff = `-- name: CreateStaff :one
INSERT INTO staff_user (username, email, password_hash)
VALUES ($1, $2, $3)
RETURNING id, username, email, password_hash, created_at
`

type CreateStaffParams struct {
	Username     string
	Email        string
	PasswordHash string
}

func (q *Queries) CreateStaff(ctx context.Context, arg CreateStaffParams) (StaffUser, error) {
	row := q.db.QueryRow(ctx, createStaff, arg.Username, arg.Email, arg.PasswordHash)
	var i StaffUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getStaffByUsername = `-- name: GetStaffByUsername :one
SELECT id, username, email, password_hash, created_at
FROM staff_user
WHERE username = $1
`

func (q *Queries) GetStaffByUsername(ctx context.Context, username string) (StaffUser, error) {
	row := q.db.QueryRow(ctx, getStaffByUsername, username)
	var i StaffUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}
