// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: treatment_case.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTreatmentCase = `-- name: CreateTreatmentCase :one
INSERT INTO treatment_case (remedy_id, healer_id, patient_age, patient_sex, symptoms, result, note, treated_on)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, remedy_id, healer_id, patient_age, patient_sex, symptoms, result, note, treated_on, created_at, updated_at
`

type CreateTreatmentCaseParams struct {
	RemedyID   int64
	HealerID   int64
	PatientAge int32
	PatientSex string
	Symptoms   string
	Result     string
	Note       string
	TreatedOn  pgtype.Date
}

func (q *Queries) CreateTreatmentCase(ctx context.Context, arg CreateTreatmentCaseParams) (TreatmentCase, error) {
	row := q.db.QueryRow(ctx, createTreatmentCase,
		arg.RemedyID,
		arg.HealerID,
		arg.PatientAge,
		arg.PatientSex,
		arg.Symptoms,
		arg.Result,
		arg.Note,
		arg.TreatedOn,
	)
	var i TreatmentCase
	err := row.Scan(
		&i.ID,
		&i.RemedyID,
		&i.HealerID,
		&i.PatientAge,
		&i.PatientSex,
		&i.Symptoms,
		&i.Result,
		&i.Note,
		&i.TreatedOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTreatmentCase = `-- name: DeleteTreatmentCase :execrows
DELETE FROM treatment_case WHERE id = $1
`

func (q *Queries) DeleteTreatmentCase(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTreatmentCase, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTreatmentCase = `-- name: GetTreatmentCase :one
SELECT id, remedy_id, healer_id, patient_age, patient_sex, symptoms, result, note, treated_on, created_at, updated_at
FROM treatment_case
WHERE id = $1
`

func (q *Queries) GetTreatmentCase(ctx context.Context, id int64) (TreatmentCase, error) {
	row := q.db.QueryRow(ctx, getTreatmentCase, id)
	var i TreatmentCase
	err := row.Scan(
		&i.ID,
		&i.RemedyID,
		&i.HealerID,
		&i.PatientAge,
		&i.PatientSex,
		&i.Symptoms,
		&i.Result,
		&i.Note,
		&i.TreatedOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTreatmentCaseByRemedy = `-- name: ListTreatmentCaseByRemedy :many
SELECT id, remedy_id, healer_id, patient_age, patient_sex, symptoms, result, note, treated_on, created_at, updated_at
FROM treatment_case
WHERE remedy_id = $1
ORDER BY treated_on DESC, id DESC
`

func (q *Queries) ListTreatmentCaseByRemedy(ctx context.Context, remedyID int64) ([]TreatmentCase, error) {
	rows, err := q.db.Query(ctx, listTreatmentCaseByRemedy, remedyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TreatmentCase{}
	for rows.Next() {
		var i TreatmentCase
		if err := rows.Scan(
			&i.ID,
			&i.RemedyID,
			&i.HealerID,
			&i.PatientAge,
			&i.PatientSex,
			&i.Symptoms,
			&i.Result,
			&i.Note,
			&i.TreatedOn,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTreatmentCase = `-- name: UpdateTreatmentCase :one
UPDATE treatment_case
SET patient_age = $2, patient_sex = $3, symptoms = $4, result = $5, note = $6, treated_on = $7, updated_at = now()
WHERE id = $1
RETURNING id, remedy_id, healer_id, patient_age, patient_sex, symptoms, result, note, treated_on, created_at, updated_at
`

type UpdateTreatmentCaseParams struct {
	ID         int64
	PatientAge int32
	PatientSex string
	Symptoms   string
	Result     string
	Note       string
	TreatedOn  pgtype.Date
}

func (q *Queries) UpdateTreatmentCase(ctx context.Context, arg UpdateTreatmentCaseParams) (TreatmentCase, error) {
	row := q.db.QueryRow(ctx, updateTreatmentCase,
		arg.ID,
		arg.PatientAge,
		arg.PatientSex,
		arg.Symptoms,
		arg.Result,
		arg.Note,
		arg.TreatedOn,
	)
	var i TreatmentCase
	err := row.Scan(
		&i.ID,
		&i.RemedyID,
		&i.HealerID,
		&i.PatientAge,
		&i.PatientSex,
		&i.Symptoms,
		&i.Result,
		&i.Note,
		&i.TreatedOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
