app_dir: /opt/thai-folk-medicine
registry: ghcr.io/willywotz
image_backend: thai-folk-medicine-backend
image_frontend: thai-folk-medicine-frontend
frontend_port: 14285
nginx_server_name: _
nginx_conf_name: thai-folk-medicine.conf
